### ISSUE TITLE
Unable to create XML template using Order Object

### ISSUE THREAD

**Issue by MohammadTF** [mPAY24/mpay24_php_api#4]
https://github.com/mPAY24/mpay24_php_api/wiki/How-to-work-with-ORDER-objects

I was testing mPay24 code as instructed by above link but I can't make XML template.

It gives me following error:
"The schema you have created is not valid!

Element 'TemplateSet': This element is not expected. Expected is one of ( Currency, Customer, BillingAddr, ShippingAddr, URL )."

**Comment by MohammadTF** [comment]
This is my generated XML template
`<?xml version="1.0" encoding="UTF-8"?>
<Order>
  <UserField>My User Field</UserField>
  <Tid>My first order</Tid>
  <Price>30.35</Price>
  <TemplateSet Language="DE">WEB</TemplateSet>
  <ShoppingCart>
    <Description>Order Description</Description>
    <Item>
      <Number>Item Number 1</Number>
      <ProductNr>Product Number 1</ProductNr>
      <Description>Description 1</Description>
      <Package>Package 1</Package>
      <Quantity>2</Quantity>
      <ItemPrice Tax="1.23">12.34</ItemPrice>
      <Price>24.68</Price>
    </Item>
    <Item>
      <Number>Item Number 2</Number>
      <ProductNr>Product Number 2</ProductNr>
      <Description>Description 2</Description>
      <Package>Package 2</Package>
      <Quantity>1</Quantity>
      <ItemPrice>5.67</ItemPrice>
      <Price>5.67</Price>
    </Item>
  </ShoppingCart>
  <Currency>USD</Currency>
  <Customer UseProfile="true" Id="98765">Hans Mayer</Customer>
  <BillingAddr Mode="ReadOnly">
    <Name>Max Musterman</Name>
    <Street>Teststreet 1</Street>
    <Street2>Teststreet 2</Street2>
    <Zip>1010</Zip>
    <City>Wien</City>
    <Country Code="AT"/>
    <Email>a.b@c.de</Email>
  </BillingAddr>
  <URL>
    <Success>http://localhost/mpay24_php_api/success.php</Success>
    <Confirmation>http://localhost/mpay24_php_api/confirm.php</Confirmation>
  </URL>
</Order>
`

**Comment by BJockeyR** [comment]
Hello MohammadTF,

i don't know if you need it since your issue is an older one, but i got the same problem today, looks like you have to stick to the defined Order of Elements inside the Order Element:

```
<xs:sequence>
<xs:element name="ClientIP" type="ClientIPType" minOccurs="0"/>
<xs:element name="UserField" minOccurs="0">...</xs:element>
<xs:element name="Tid">...</xs:element>
<xs:element name="TemplateSet" minOccurs="0">...</xs:element>
<xs:element name="PaymentTypes" minOccurs="0">...</xs:element>
<xs:element name="PaymentProfiles" minOccurs="0">...</xs:element>
<xs:element name="ShoppingCart" minOccurs="0">...</xs:element>
<xs:element name="Price">...</xs:element>
<xs:element name="Currency" minOccurs="0">...</xs:element>
<xs:element name="Customer" minOccurs="0">...</xs:element>
<xs:element name="BillingAddr" minOccurs="0">...</xs:element>
<xs:element name="ShippingAddr" minOccurs="0">...</xs:element>
<xs:element name="URL" minOccurs="0">...</xs:element>
</xs:sequence>
```

this Order worked for me

**Comment by tobiaslins** [comment]
Hi @MohammadTF 

The Element `Price` is expected after `ShoppingCart`.

This is your working Order XML:
```xml
<Order>
  <UserField>My User Field</UserField>
  <Tid>My first order</Tid>
  <TemplateSet Language="DE">WEB</TemplateSet>
  <ShoppingCart>
    <Description>Order Description</Description>
    <Item>
      <Number>Item Number 1</Number>
      <ProductNr>Product Number 1</ProductNr>
      <Description>Description 1</Description>
      <Package>Package 1</Package>
      <Quantity>2</Quantity>
      <ItemPrice Tax="1.23">12.34</ItemPrice>
      <Price>24.68</Price>
    </Item>
    <Item>
      <Number>Item Number 2</Number>
      <ProductNr>Product Number 2</ProductNr>
      <Description>Description 2</Description>
      <Package>Package 2</Package>
      <Quantity>1</Quantity>
      <ItemPrice>5.67</ItemPrice>
      <Price>5.67</Price>
    </Item>
  </ShoppingCart>
  <Price>30.35</Price>
  <Currency>USD</Currency>
  <Customer UseProfile="true" Id="98765">Hans Mayer</Customer>
  <BillingAddr Mode="ReadOnly">
    <Name>Max Musterman</Name>
    <Street>Teststreet 1</Street>
    <Street2>Teststreet 2</Street2>
    <Zip>1010</Zip>
    <City>Wien</City>
    <Country Code="AT" />
    <Email>a.b@c.de</Email>
  </BillingAddr>
  <URL>
    <Success>http://localhost/mpay24_php_api/success.php</Success>
    <Confirmation>http://localhost/mpay24_php_api/confirm.php</Confirmation>
  </URL>
</Order>
```
